buy_box:
  outputs:
    dev:
      account: jyvbwgv-llb12765
      type: snowflake
      user: Sivateja2001
      password: Sivateja#2003
      database: AIRFLOW
      role: ACCOUNTADMIN
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev



# outputs:
#     dev:
#       account: pk18845.us-east-2.aws
#       database: BUYBOX
#       password: Sivateja#2003
#       role: TRANSFORM
#       schema: DEV
#       threads: 1
#       type: snowflake
#       user: Sivateja2001
#       warehouse: COMPUTE_WH
# astro dev start
# astro dev stop
# astro dev restart